// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package repository is a generated GoMock package.
package repository

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	hotel "tourtoster/hotel"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Hotel mocks base method
func (m *MockRepository) Hotel(ID int64) (*hotel.Hotel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hotel", ID)
	ret0, _ := ret[0].(*hotel.Hotel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hotel indicates an expected call of Hotel
func (mr *MockRepositoryMockRecorder) Hotel(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hotel", reflect.TypeOf((*MockRepository)(nil).Hotel), ID)
}

// HotelByName mocks base method
func (m *MockRepository) HotelByName(name string) (*hotel.Hotel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HotelByName", name)
	ret0, _ := ret[0].(*hotel.Hotel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HotelByName indicates an expected call of HotelByName
func (mr *MockRepositoryMockRecorder) HotelByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HotelByName", reflect.TypeOf((*MockRepository)(nil).HotelByName), name)
}

// Save mocks base method
func (m *MockRepository) Save(h *hotel.Hotel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockRepositoryMockRecorder) Save(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), h)
}

// Delete mocks base method
func (m *MockRepository) Delete(ID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ID)
}

// List mocks base method
func (m *MockRepository) List() ([]hotel.Hotel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]hotel.Hotel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List))
}
